// student-manager-angular/src/app/admin-login/admin-login.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

const API_URL = 'https://localhost:7003/api/Users/admin-login';

@Component({
  selector: 'app-admin-login',
  templateUrl: './admin-login.html',
  styleUrls: ['./admin-login.css'],
  standalone: true,
  imports: [CommonModule, FormsModule],
})
export class AdminLogin {
  form = { email: '', password: '' };
  showPassword = false;

  constructor(private router: Router) {}

  handleChange(event: any) {
    const { name, value } = event.target;
    this.form = { ...this.form, [name]: value };
  }

  async handleLogin(event: Event) {
    event.preventDefault();
    try {
      const res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(this.form),
      });

      if (res.ok) {
        const data = await res.json();
        localStorage.setItem('admin', JSON.stringify(data.user));
        localStorage.setItem('adminToken', data.token);
        alert('Admin login successful!');
        setTimeout(() => this.router.navigate(['/AdminDashboard']), 1000);
      } else {
        const err = await res.text();
        alert(err);
      }
    } catch {
      alert('Something went wrong!');
    }
  }

  toggleShowPassword() {
    this.showPassword = !this.showPassword;
  }

  onMouseOver(event: MouseEvent) {
    const target = event.target as HTMLElement | null;
    if (target) {
      target.style.background = '#1a5edb';
    }
  }

  onMouseOut(event: MouseEvent) {
    const target = event.target as HTMLElement | null;
    if (target) {
      target.style.background = '#2575fc';
    }
  }
}

// student-manager/src/AdminLogin.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast, ToastContainer } from "react-toastify";
import { FaEye, FaEyeSlash } from "react-icons/fa";
import "react-toastify/dist/ReactToastify.css";

const API_URL = "https://localhost:7003/api/Users/admin-login"; 

export default function AdminLogin() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    email: "",
    password: "",
  });

  const [showPassword, setShowPassword] = useState(false);

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      const res = await fetch(API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });

      if (res.ok) {
        const data = await res.json();

        //  Save Admin user info
        localStorage.setItem("admin", JSON.stringify(data.user));
        localStorage.setItem("adminToken", data.token);

        toast.success("Admin login successful!");
        setTimeout(() => navigate("/AdminDashboard"), 1000);
      } else {
        const err = await res.text();
        toast.error(err);
      }
    } catch (error) {
      toast.error("Something went wrong!");
    }
  };

  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        minHeight: "100vh",
        background: "linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)",
        fontFamily: "Segoe UI, Tahoma, Geneva, Verdana, sans-serif",
      }}
    >
      <div
        style={{
          background: "#fff",
          padding: "30px 40px",
          borderRadius: "12px",
          boxShadow: "0 4px 15px rgba(0,0,0,0.1)",
          width: "100%",
          maxWidth: "400px",
          textAlign: "center",
        }}
      >
        <h2 style={{ marginBottom: "20px", color: "#333" }}>Admin Login</h2>
        <form onSubmit={handleLogin}>
          <input
            type="email"
            name="email"
            placeholder="Admin Email"
            value={form.email}
            onChange={handleChange}
            required
            style={{
              width: "100%",
              padding: "12px",
              margin: "10px 0",
              borderRadius: "8px",
              border: "1px solid #ccc",
              outline: "none",
              fontSize: "14px",
            }}
          />
          <div style={{ position: "relative" }}>
            <input
              type={showPassword ? "text" : "password"}
              name="password"
              placeholder="Password"
              value={form.password}
              onChange={handleChange}
              required
              style={{
                width: "100%",
                padding: "12px",
                margin: "10px 0",
                borderRadius: "8px",
                border: "1px solid #ccc",
                outline: "none",
                fontSize: "14px",
                paddingRight: "10px",
              }}
            />
            <span
              onClick={() => setShowPassword(!showPassword)}
              style={{
                position: "absolute",
                right: "12px",
                top: "50%",
                transform: "translateY(-50%)",
                cursor: "pointer",
                color: "#666",
              }}
            >
              {showPassword ? <FaEyeSlash /> : <FaEye />}
            </span>
          </div>
          <button
            type="submit"
            style={{
              width: "100%",
              padding: "12px",
              marginTop: "15px",
              background: "#2575fc",
              color: "#fff",
              border: "none",
              borderRadius: "8px",
              fontSize: "16px",
              fontWeight: "bold",
              cursor: "pointer",
              transition: "0.3s",
            }}
            onMouseOver={(e) => (e.target.style.background = "#1a5edb")}
            onMouseOut={(e) => (e.target.style.background = "#2575fc")}
          >
            Admin Login
          </button>
        </form>
        <ToastContainer position="top-right" autoClose={2000} />
      </div>
    </div>
  );
}
